// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/profile/:id": {
    params: {
      "id": string;
    };
  };
  "/post/:id": {
    params: {
      "id": string;
    };
  };
  "/group-post/:id": {
    params: {
      "id": string;
    };
  };
  "/groups": {
    params: {};
  };
  "/create-group": {
    params: {};
  };
  "/group/:id": {
    params: {
      "id": string;
    };
  };
  "/marketplace": {
    params: {};
  };
  "/create-listing": {
    params: {};
  };
  "/listing/:id": {
    params: {
      "id": string;
    };
  };
  "/my-orders": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/resource/:id": {
    params: {
      "id": string;
    };
  };
  "/upload-resource": {
    params: {};
  };
  "/grievances": {
    params: {};
  };
  "/file-grievance": {
    params: {};
  };
  "/grievance/:id": {
    params: {
      "id": string;
    };
  };
  "/crisis": {
    params: {};
  };
  "/create-alert": {
    params: {};
  };
  "/crisis/:id": {
    params: {
      "id": string;
    };
  };
  "/compliance": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/messages/:userId": {
    params: {
      "userId": string;
    };
  };
  "/events": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/new-post": {
    params: {};
  };
  "/admin/grievances": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/onboarding" | "/feed" | "/profile/:id" | "/post/:id" | "/group-post/:id" | "/groups" | "/create-group" | "/group/:id" | "/marketplace" | "/create-listing" | "/listing/:id" | "/my-orders" | "/resources" | "/resource/:id" | "/upload-resource" | "/grievances" | "/file-grievance" | "/grievance/:id" | "/crisis" | "/create-alert" | "/crisis/:id" | "/compliance" | "/messages" | "/messages/:userId" | "/events" | "/analytics" | "/new-post" | "/admin/grievances" | "/admin/users";
  };
  "layouts/PublicLayout.jsx": {
    id: "layouts/PublicLayout";
    page: "/" | "/login" | "/signup";
  };
  "pages/Landing.jsx": {
    id: "pages/Landing";
    page: "/";
  };
  "pages/Login.jsx": {
    id: "pages/Login";
    page: "/login";
  };
  "pages/Signup.jsx": {
    id: "pages/Signup";
    page: "/signup";
  };
  "layouts/OnboardingLayout.jsx": {
    id: "layouts/OnboardingLayout";
    page: "/onboarding";
  };
  "pages/Onboarding.jsx": {
    id: "pages/Onboarding";
    page: "/onboarding";
  };
  "layouts/ProtectedLayout.jsx": {
    id: "layouts/ProtectedLayout";
    page: "/feed" | "/profile/:id" | "/post/:id" | "/group-post/:id" | "/groups" | "/create-group" | "/group/:id" | "/marketplace" | "/create-listing" | "/listing/:id" | "/my-orders" | "/resources" | "/resource/:id" | "/upload-resource" | "/grievances" | "/file-grievance" | "/grievance/:id" | "/crisis" | "/create-alert" | "/crisis/:id" | "/compliance" | "/messages" | "/messages/:userId" | "/events" | "/analytics" | "/new-post";
  };
  "pages/Feed.jsx": {
    id: "pages/Feed";
    page: "/feed";
  };
  "pages/Profile.jsx": {
    id: "pages/Profile";
    page: "/profile/:id";
  };
  "pages/PostDetails.jsx": {
    id: "pages/PostDetails";
    page: "/post/:id";
  };
  "pages/GroupPostDetails.jsx": {
    id: "pages/GroupPostDetails";
    page: "/group-post/:id";
  };
  "pages/Groups.jsx": {
    id: "pages/Groups";
    page: "/groups";
  };
  "pages/CreateGroup.jsx": {
    id: "pages/CreateGroup";
    page: "/create-group";
  };
  "pages/GroupDetails.jsx": {
    id: "pages/GroupDetails";
    page: "/group/:id";
  };
  "pages/marketplace/Marketplace.jsx": {
    id: "pages/marketplace/Marketplace";
    page: "/marketplace";
  };
  "pages/CreateListing.jsx": {
    id: "pages/CreateListing";
    page: "/create-listing";
  };
  "pages/ListingDetails.jsx": {
    id: "pages/ListingDetails";
    page: "/listing/:id";
  };
  "pages/MyOrders.jsx": {
    id: "pages/MyOrders";
    page: "/my-orders";
  };
  "pages/Resources.jsx": {
    id: "pages/Resources";
    page: "/resources";
  };
  "pages/ResourceDetails.jsx": {
    id: "pages/ResourceDetails";
    page: "/resource/:id";
  };
  "pages/UploadResource.jsx": {
    id: "pages/UploadResource";
    page: "/upload-resource";
  };
  "pages/Grievances.jsx": {
    id: "pages/Grievances";
    page: "/grievances";
  };
  "pages/FileGrievance.jsx": {
    id: "pages/FileGrievance";
    page: "/file-grievance";
  };
  "pages/GrievanceDetails.jsx": {
    id: "pages/GrievanceDetails";
    page: "/grievance/:id";
  };
  "pages/CrisisAlerts.jsx": {
    id: "pages/CrisisAlerts";
    page: "/crisis";
  };
  "pages/CreateAlert.jsx": {
    id: "pages/CreateAlert";
    page: "/create-alert";
  };
  "pages/CrisisDetails.jsx": {
    id: "pages/CrisisDetails";
    page: "/crisis/:id";
  };
  "pages/Compliance.jsx": {
    id: "pages/Compliance";
    page: "/compliance";
  };
  "pages/Messages.jsx": {
    id: "pages/Messages";
    page: "/messages";
  } | {
    id: "messages-userId";
    page: "/messages/:userId";
  };
  "pages/Events.jsx": {
    id: "pages/Events";
    page: "/events";
  };
  "pages/Analytics.jsx": {
    id: "pages/Analytics";
    page: "/analytics";
  };
  "pages/NewPost.jsx": {
    id: "pages/NewPost";
    page: "/new-post";
  };
  "layouts/AdminLayout.jsx": {
    id: "layouts/AdminLayout";
    page: "/admin/grievances" | "/admin/users";
  };
  "pages/AdminGrievances.jsx": {
    id: "pages/AdminGrievances";
    page: "/admin/grievances";
  };
  "pages/AdminUsers.jsx": {
    id: "pages/AdminUsers";
    page: "/admin/users";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "layouts/PublicLayout": typeof import("./src/layouts/PublicLayout.jsx");
  "pages/Landing": typeof import("./src/pages/Landing.jsx");
  "pages/Login": typeof import("./src/pages/Login.jsx");
  "pages/Signup": typeof import("./src/pages/Signup.jsx");
  "layouts/OnboardingLayout": typeof import("./src/layouts/OnboardingLayout.jsx");
  "pages/Onboarding": typeof import("./src/pages/Onboarding.jsx");
  "layouts/ProtectedLayout": typeof import("./src/layouts/ProtectedLayout.jsx");
  "pages/Feed": typeof import("./src/pages/Feed.jsx");
  "pages/Profile": typeof import("./src/pages/Profile.jsx");
  "pages/PostDetails": typeof import("./src/pages/PostDetails.jsx");
  "pages/GroupPostDetails": typeof import("./src/pages/GroupPostDetails.jsx");
  "pages/Groups": typeof import("./src/pages/Groups.jsx");
  "pages/CreateGroup": typeof import("./src/pages/CreateGroup.jsx");
  "pages/GroupDetails": typeof import("./src/pages/GroupDetails.jsx");
  "pages/marketplace/Marketplace": typeof import("./src/pages/marketplace/Marketplace.jsx");
  "pages/CreateListing": typeof import("./src/pages/CreateListing.jsx");
  "pages/ListingDetails": typeof import("./src/pages/ListingDetails.jsx");
  "pages/MyOrders": typeof import("./src/pages/MyOrders.jsx");
  "pages/Resources": typeof import("./src/pages/Resources.jsx");
  "pages/ResourceDetails": typeof import("./src/pages/ResourceDetails.jsx");
  "pages/UploadResource": typeof import("./src/pages/UploadResource.jsx");
  "pages/Grievances": typeof import("./src/pages/Grievances.jsx");
  "pages/FileGrievance": typeof import("./src/pages/FileGrievance.jsx");
  "pages/GrievanceDetails": typeof import("./src/pages/GrievanceDetails.jsx");
  "pages/CrisisAlerts": typeof import("./src/pages/CrisisAlerts.jsx");
  "pages/CreateAlert": typeof import("./src/pages/CreateAlert.jsx");
  "pages/CrisisDetails": typeof import("./src/pages/CrisisDetails.jsx");
  "pages/Compliance": typeof import("./src/pages/Compliance.jsx");
  "pages/Messages": typeof import("./src/pages/Messages.jsx");
  "messages-userId": typeof import("./src/pages/Messages.jsx");
  "pages/Events": typeof import("./src/pages/Events.jsx");
  "pages/Analytics": typeof import("./src/pages/Analytics.jsx");
  "pages/NewPost": typeof import("./src/pages/NewPost.jsx");
  "layouts/AdminLayout": typeof import("./src/layouts/AdminLayout.jsx");
  "pages/AdminGrievances": typeof import("./src/pages/AdminGrievances.jsx");
  "pages/AdminUsers": typeof import("./src/pages/AdminUsers.jsx");
};